version: '3.8'

services:
  app:
    build: .
    container_name: bboard-frontend
    network_mode: host
    restart: always

  server:
    build: ./server
    container_name: bboard-backend
    network_mode: host
    volumes:
      - ./server/database.sqlite:/app/database.sqlite
    restart: always
